### PR TITLE
Add some PT translations.

### PR DESCRIPTION
**Pull request by sayrer**
Hi

@apfernandes please check this one. I was checking my work and it kept saying "o Callsheet", like "the Callsheet", but it didn't sound right to me. So I left it out. But this is a common Portuguese/English problem. Not sure what sounds best.

### CODE REVIEW

**Review by cliss — APPROVED** [review]

**Comment by apfernandes** [comment]
Hi Casey, I need little more context. In Portuguese the word Application is feminin so we would translate. 
"...the APP Callsheet..." to "A APP Callsheet"
Callsheet has no feminine or maculine so the way I normally do it is avoiding to have to use "a" or "o" (feminine or masculine).
I work around the wording by using for instance
"With Callsheet..."
"Com Callsheet..." 
or force the APP word before the name and there use the "a"
"... with Callsheet..."
"... com a APP Callsheet..."

Again, let me know of the context and I will suggest further options from the "uncomplicated Portuguese language"...

I have not been following this repository lately but if there is more stuff to translate ping me anytime, I will find time to do it. Cheers!

**Comment by apfernandes** [comment]
Not sure if your comment is from today! Sorry, but I got a github email just now as if you had commented it...

**Comment by cliss** [comment]
Depends on the line in question, but generally, it seems like this is related to subscription problems:

Screenshot 2024-08-01 at 9 56 14 AM

**Comment by sayrer** [comment]
For some context from the English side, the issue is that it gets mistranslated. The most famous one is "Oporto" instead of just "Porto". The grammatical gender matches, but it's like saying "The Paris" instead of just "Paris".

**Comment by apfernandes** [comment]
Looking at it again I would prefer just to add the word "aplicação" (APP) before Callsheet and so force the use of the feminine form (for the word aplicação). Sorry but Portuguese is not as succinct as English
-> O seu acesso à aplicação Callsheet terminará em ...
-> Saber pais sobre as pessoas por detrás da aplicação Callsheet
-> A sua assinatura expirou. Para continuar a utilizar a aplicação Callsheet, terá de iniciar uma novas subscrição
-> Force modo de apresentação a partir da aplicação Callsheet ou utilize as definições de sistema
-> Aceder à aplicação Callsheet durante 1 ano. Renova automaticamente
-> Classifique esta versão da aplicação Callsheet

**Comment by sayrer** [comment]
That sounds right to me. I can read it well enough, but it can be tough to write idiomatically, especially in computer words.

Should it be this way?

"Saber **mais** sobre as pessoas por detrás da aplicação Callsheet"

As for the succinct qualities of English, I don't see it that way. Most languages run at about the same information density. Spanish and Portuguese might look superficially verbose, but that's why they sound so fast when spoken. You can move faster :)

**Comment by sayrer** [comment]
Hi @apfernandes, do you want to do these? I'm happy to do them as I know my way around XCode more than Portuguese, but you wrote it all.

**Comment by apfernandes** [comment]
@sayrer Please go ahead. I am short on spare time. Thank you! 

"Saber mais sobre as pessoas por detrás da aplicação Callsheet"  - yes, I had a typo, sorry :)

**Pull request merged**
