### PR TITLE
First version of Dutch translation. 

### PR DESCRIPTION
**Pull request by Deddiekoel**
Tried to keep english capitalization. Did some fairly straight translations that may need a better in-spirit translation.

### CODE REVIEW

**Comment by cliss** [comment]
Thanks so much, @Deddiekoel! I actually found some more things that need to be translated thanks to our 🇺🇦  and 🇩🇪  friends; would you mind pulling in the latest from upstream, adding those, and then re-committing please? I'm happy to merge once that's all done. :)

**Comment by Deddiekoel** [comment]
Sure, just let me figure out how...

**Comment by cliss** [comment]
General gist is:

1) Merge from `cliss:main` → `Deddiekoel:main`
2) Make your new changes
3) Commit the new changes
4) Comment here so I know I need to look again :)

If you can't get it squared away quickly, let me know. This isn't designed to cost you many hours of your time! 😬

**Comment by Deddiekoel** [comment]
Ok, just threw away my local repo (after copying the nl.xcloc package) and cloned again. Then copied it back in and committed...

**Pull request closed without merging**
