### PR TITLE
Spanish Localization finished

### PR DESCRIPTION
**Pull request by unaiherran**
Done by a human being, not a pesky translation service from a fruit company

### CODE REVIEW

**Comment by unaiherran** [comment]
Some guesses were made for some strings, that no matter how much I tried I wasn't able to find in the app. A testflight access to verify the localization in the real app will surely be helpful

**Comment by technocidal** [comment]
Until that TestFlight invite arrives, feel free to put your questions here. We've clarified a lot of stuff with @cliss already while translating into other languages so we might be able to help you already. I imagine that some questions might overlap and there is no fun in reading through a bunch of closed PRs.

**Comment by sayrer** [comment]
That's awesome. I can speak these somewhat, but it takes a native speaker to get things like "autoplaying video". I tried doing the App Store description in French (and I lived in France as a kid), but ran into that right away. The internet words are tough.

Do you think you an es-419 one is needed, or is it pretty much the same because the phrases are short?

https://stackoverflow.com/questions/56940160/what-is-the-difference-between-es-and-es-419-in-ios-localization

**Comment by unaiherran** [comment]
I think it will probably will be the same, since most of the words are short, but sometimes there are word in es-es that have completely different meaning in  es419. Sadly I’m a native es-es, and even though I’m familiar with some of them, for sure I can make mistakes.  I will try to run it by some colleagues (that insist in speaking Argentinian instead of Spanish 😁)Probably the best course of action is to finish (and proofread) the es-es and fork from there by a native es419--Unai HerránEl 19 may 2024, a las 1:00, RS ***@***.***> escribió:﻿
That's awesome. I can speak these somewhat, but it takes a native speaker to get things like "autoplaying video". I tried doing the App Store description in French (and I lived in France as a kid), but ran into that right away. The internet words are tough.
Do you think you an es-419 one is needed, or is it pretty much the same because the phrases are short?
https://stackoverflow.com/questions/56940160/what-is-the-difference-between-es-and-es-419-in-ios-localization

**Comment by unaiherran** [comment]
The one I can think of now is landscape, which I don’t know if it speaks about orientation (portrait/landscape) or sceneryAlso there are some strings that are the same, only capitalization is different, where I tried to respect it, but will need to see them in context to make sure they are the correct ones. Anyhow, every time I made a translation there is the need to have multiple passes and checks before it can be released. There are always weird effects, that surface in the final product. --Unai HerránEl 18 may 2024, a las 22:36, Johannes Ebeling ***@***.***> escribió:﻿
Until that TestFlight invite arrives, feel free to put your questions here. We've clarified a lot of stuff with @cliss already while translating into other languages so we might be able to help you already. I imagine that some questions might overlap and there is no fun in reading through a bunch of closed PRs.

**Comment by sayrer** [comment]
That all makes sense to me. I think if there needs to be some specialized Spanish, the es-419 stuff should work from Mexico to Peru (and thus capture all of the TV shows and soap operas). The Rioplatense Spanish (Argentina and Uruguay) is a smaller market. It is also real, though. They love Viggo Mortensen, because he can speak that Spanish (which is difficult for me, but I think they can understand regular 419 easily)

**Comment by technocidal** [comment]
@unaiherran In German we decided not to follow the English capitalization for those particular phrases because it's more common to always have the verb lower case (e.g. Add Pin -> Pin hinzufügen).

I think I've found the place in the translations you talk about in regards to landscape, but I'm unable to find that string in the app. I've checked using voice over as well as it might be an accessibility label, but no luck. Sorry.

**Comment by cliss** [comment]
> I think I've found the place in the translations you talk about in regards to landscape, but I'm unable to find that string in the app. I've checked using voice over as well as it might be an accessibility label, but no luck. Sorry.

What's the actual string? I'm happy to search and clarify. :)

**Comment by cliss** [comment]
@unaiherran Please feel free to let me know your TestFlight email via [Mastodon](https://mastodon.social/@caseyliss) or [email](https://www.caseyliss.com/contact) and I'll add you! Thanks for taking a pass at this!!

**Review by cliss — APPROVED** [review]

**Comment by unaiherran** [comment]
The Id was Portrait., my memory played a trick on me. 

And probably has to do more with Portrait as in portrait of a person than portrait in the portrait/landscape meaning

**Comment by cliss** [comment]
Ah, yes, that's about a person's portrait, not a aspect ratio. :)

**Pull request merged**
