### PR TITLE
Dutch: last one 🤞

### PR DESCRIPTION
**Pull request by Deddiekoel**
I will not be denied!

(hope this is the last one, for now)

### CODE REVIEW

**Comment by cliss** [comment]
I have bad news for you 😬 

https://github.com/cliss/callsheet-localizations/pull/54#issuecomment-2127884468

**Comment by cliss** [comment]
Also, as per Github, there's no changes in this PR. 🤨 

I suspect there's some sort of oddity here that is likely not your fault.

**Comment by Deddiekoel** [comment]
Ok, pushed everything again. Confirmed the translation in the fork. Hopefully it took now...

**Review by cliss — APPROVED** [review]

**Comment by cliss** [comment]
Thanks! These are still missing:

Screenshot 2024-05-23 at 6 53 31 PM

**Pull request merged**
