### PR TITLE
Portuguese (Portugal) further updates

### PR DESCRIPTION
**Pull request by apfernandes**
Portuguese (Portugal) further updates

### CODE REVIEW

**Review by cliss — CHANGES_REQUESTED** [review]
I don't think the changes to `Localizable.xcstrings` was deliberate, right?

Can you revert that file, please? And then I'll merge.

**Comment by apfernandes** [comment]
Sorry, I messed up because I copied a file form a previous version. Hopefully I got it right now

**Review by cliss — APPROVED** [review]
Thank you!

**Comment by apfernandes** [comment]
I think that I have already translated everything. I will perform one last review again, hopefully tomorrow.

**Pull request merged**
