### PR TITLE
IT translation of newly added strings

### PR DESCRIPTION
**Pull request by cdf1982**

### CODE REVIEW

**Comment by cdf1982** [comment]
I was wondering... what about the App Store description? It's certainly a bit more work, but probably the most bang for the buck in terms of non-English speakers browsing the App Store. And when you're at that, keywords...
Personally, I'll never do localised screenshots again, it's already such pain...

**Comment by cliss** [comment]
@cdf1982 I'd *love* to get the description localized; I didn't want to ask for too much from y'all, and I'm not _entirely_ sure the best way to do it. Maybe I'll add a folder peer to `CallsheetLocalizations` with some raw `txt` files in it…? 🤷

**Comment by cdf1982** [comment]
@cliss personally, I'd wouldn't mind helping with the description, if you decide to pull the trigger. And I'm sure others would love to help too for their languages.
Txt files is a reasonable way to go, IMHO, and indeed I've seen that method used in the past by other apps.

**Review by cliss — APPROVED** [review]

**Comment by cliss** [comment]
@cdf1982 Just in case you didn't see it: https://github.com/cliss/callsheet-localizations/tree/main/AppStore/English

**Comment by cliss** [comment]
> First time working on a version-controlled project with a members' count greater than one 😉... do I need to create a pull request each time?

Yeah, since you're in your own fork — as I requested! — you'll need to:

1) Pull the latest from my `main` into your branch (which is part of your fork)
2) Merge if necessary
3) [If possible] double-check there aren't any other new strings that have been added, which there are, because I just did it haha
4) Commit to your branch
5) Issue a new PR

I know it's kind of a lot, but it's the best way I know how to do it.

>A couple of notes on the translated descriptions:
>
> * I have "balanced" genders: "Ti sei mai chiesto" in the first sentence is male, "Magari sei un appassionata di film e ti sei chiesta" in the second is female. To me, it makes sense and sounds good, but let me know if you need changes.

👍🏻 

> * In visionOS, I removed the reference to the customisable app icons, as my (very envious non-owner) understanding is that they're not yet supported.

Damnit, whoops, I should do that for English too!

**Comment by Deddiekoel** [comment]
Ok, to be able to merge I first had to add your 'fork' as the upstream 'branch':
`git remote add upstream https://github.com/cliss/callsheet-localizations.git`
From there I could pull from there in Xcode and use that to handle the merge. The new (?) status on the translation entries was most of the conflicts.

Pushing a new PR now.

**Pull request merged**
