### PR TITLE
Second pass for Russian translation

### PR DESCRIPTION
**Pull request by gkeep**
Mostly made changes to better fit localized strings into UI. Also fixed a typo or two.

### CODE REVIEW

**Comment by gkeep** [comment]
Don't merge yet. Will do the App Store description soon

**Comment by cliss** [comment]
Similarly, please add new strings that I added in 58c82df0bc8eb5a00080f94b6e64fdfac64a68b4 :)

**Review by cliss — CHANGES_REQUESTED** [review]
Please add new strings from 58c82df0bc8eb5a00080f94b6e64fdfac64a68b4 😇

**Comment by gkeep** [comment]
I think I did something wrong in git... I'll just reopen this in a new PR

**Pull request closed without merging**
